// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yucrlozafkjqorqmppkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1Y3Jsb3phZmtqcW9ycW1wcGtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5Njc0ODgsImV4cCI6MjA2MjU0MzQ4OH0.seQIsRrta1KDhDqEM6SLAA3ZwTF6vOQ6S9WVeWCD7EA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);